version: '3.4'

services:
  catalog.db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: catalog_sql_server
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Sifre38901!"
    ports:
      - "1433:1433"

  catalog.api:
    container_name: ecommerce-catalog.api
    build:
      context: .
      dockerfile: src/services/CatalogService/CatalogService.API/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "Server=catalog.db,1433;Database=CatalogDb;User Id=sa;Password=Sifre38901!;TrustServerCertificate=True;Encrypt=False"
    depends_on:
      - catalog.db
  
  basket.db:
    image: redis:alpine
    container_name: basket_redis
    ports:
      - "6379:6379"

  basket.api:
    container_name: ecommerce-basket.api
    build:
      context: .
      dockerfile: src/services/BasketService/BasketService.API/Dockerfile 
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__RedisConnection: "basket.db:6379"
    depends_on:
      - basket.db

  api.gateway:
    container_name: ecommerce-api.gateway
    build:
      context: .
      dockerfile: src/services/ApiGateaway/Ecommerce.ApiGateaway/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    ports:
      - "5000:8080"
    depends_on:
      - catalog.api
      - basket.api