// <auto-generated />
using System;
using CatalogService.Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CatalogService.Infrastructure.Migrations
{
    [DbContext(typeof(CatalogDbContext))]
    [Migration("20260623175259_AddStockToProduct")]
    partial class AddStockToProduct
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CatalogService.Domain.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2026, 6, 23, 0, 0, 0, 0, DateTimeKind.Local),
                            Name = "Electronics"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2026, 6, 23, 0, 0, 0, 0, DateTimeKind.Local),
                            Name = "Computers"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2026, 6, 23, 0, 0, 0, 0, DateTimeKind.Local),
                            Name = "Accessories"
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2026, 6, 23, 0, 0, 0, 0, DateTimeKind.Local),
                            Name = "Storage"
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2026, 6, 23, 0, 0, 0, 0, DateTimeKind.Local),
                            Name = "Gaming"
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(2026, 6, 23, 0, 0, 0, 0, DateTimeKind.Local),
                            Name = "Networking"
                        },
                        new
                        {
                            Id = 7,
                            CreatedDate = new DateTime(2026, 6, 23, 0, 0, 0, 0, DateTimeKind.Local),
                            Name = "Audio"
                        },
                        new
                        {
                            Id = 8,
                            CreatedDate = new DateTime(2026, 6, 23, 0, 0, 0, 0, DateTimeKind.Local),
                            Name = "Monitors"
                        },
                        new
                        {
                            Id = 9,
                            CreatedDate = new DateTime(2026, 6, 23, 0, 0, 0, 0, DateTimeKind.Local),
                            Name = "Printers"
                        },
                        new
                        {
                            Id = 10,
                            CreatedDate = new DateTime(2026, 6, 23, 0, 0, 0, 0, DateTimeKind.Local),
                            Name = "Software"
                        });
                });

            modelBuilder.Entity("CatalogService.Domain.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2026, 6, 23, 0, 0, 0, 0, DateTimeKind.Local),
                            Description = "High performance laptop",
                            Name = "Laptop",
                            Price = 85.99m,
                            Stock = 50
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2026, 6, 23, 0, 0, 0, 0, DateTimeKind.Local),
                            Description = "Wireless optical mouse",
                            Name = "Mouse",
                            Price = 15.49m,
                            Stock = 80
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2026, 6, 23, 0, 0, 0, 0, DateTimeKind.Local),
                            Description = "Mechanical keyboard",
                            Name = "Keyboard",
                            Price = 45.00m,
                            Stock = 60
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            CreatedDate = new DateTime(2026, 6, 23, 0, 0, 0, 0, DateTimeKind.Local),
                            Description = "27 inch 4K monitor",
                            Name = "Monitor",
                            Price = 99.99m,
                            Stock = 30
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 7,
                            CreatedDate = new DateTime(2026, 6, 23, 0, 0, 0, 0, DateTimeKind.Local),
                            Description = "Noise cancelling headset",
                            Name = "Headphones",
                            Price = 55.75m,
                            Stock = 40
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 3,
                            CreatedDate = new DateTime(2026, 6, 23, 0, 0, 0, 0, DateTimeKind.Local),
                            Description = "1080p HD webcam",
                            Name = "Webcam",
                            Price = 29.99m,
                            Stock = 70
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 3,
                            CreatedDate = new DateTime(2026, 6, 23, 0, 0, 0, 0, DateTimeKind.Local),
                            Description = "7 port USB 3.0 hub",
                            Name = "USB Hub",
                            Price = 18.50m,
                            Stock = 90
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 4,
                            CreatedDate = new DateTime(2026, 6, 23, 0, 0, 0, 0, DateTimeKind.Local),
                            Description = "1TB NVMe SSD",
                            Name = "SSD",
                            Price = 72.00m,
                            Stock = 25
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 4,
                            CreatedDate = new DateTime(2026, 6, 23, 0, 0, 0, 0, DateTimeKind.Local),
                            Description = "16GB DDR5 RAM",
                            Name = "RAM",
                            Price = 63.25m,
                            Stock = 35
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 5,
                            CreatedDate = new DateTime(2026, 6, 23, 0, 0, 0, 0, DateTimeKind.Local),
                            Description = "Gaming graphics card",
                            Name = "GPU",
                            Price = 95.00m,
                            Stock = 15
                        });
                });

            modelBuilder.Entity("CatalogService.Domain.Entities.Product", b =>
                {
                    b.HasOne("CatalogService.Domain.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
